################################################################################
# dataset
################################################################################
# for testing source codes with smaller dataset

dataset:
  root : 'E:/Datasets/NuScenes/mini/v1.0-mini/v1.0-mini'
  version : 'v1.0-mini'

# un-comment this if you want to use complete dataset [training+validation] dataset

#dataset:
#  root: 'G:/nuscenes'
#  version: 'v1.0-trainval'

# [testing] dataset

#dataset:
#  root: 'G:/nuscenes'
#  version: 'v1.0-test'


total_lidar_pts : 1185656192 # In trainval v1.0 dataset

details: #indicating the number of elements from individual json file
  category : 32 # total number of classes
  attribute : 8 # object attributes[obj-det] e.g. vehicle.moving, vehicle.stopped, vehicle.parked, cycle.with_rider
                # cycle.without_rider,pedestrian.sitting_lying_down, pedestrian.standing, pedestrian.moving
  visibility : 4 # instance is the fraction of annotation visible in all 6 images [0-40,40-60,60-80,80-100]
  instance : 64386 # total number of instances in all dataset
  sensor : 12 # total number of sensors [6x camera + 1x Lidar + 5x radar]
  calibrated_sensor : 10200 # sensor calibrations
  ego_pose : 2631083  # Ego vehicle pose at a particular timestamp
  log : 68 #Information about the log from which the data was extracted
  scene : 850 # 20s long sequence of consecutive frames extracted from a log [sequences]
  sample : 34149 # Dataframe
  sample_data : 2631083 # A sensor data e.g. image, point cloud or radar return
  sample_annotation : 1166187 # A bounding box defining the position of an object seen in a sample
  map : 4 # Map data that is stored as binary semantic masks from a top-down view
  lidarseg : 34149 # Mapping between nuScenes-lidarseg annotations and sample_data
  panoptic : 34149 # Mapping between nuScenes-Panoptic annotations and sample_data


################################################################################
# class-mapping
################################################################################

weights:
  epsilon : 0.001
  learning_ignore :
    - 0


learning_map_names:
  human.pedestrian.adult: 'pedestrian'
  human.pedestrian.child: 'pedestrian'
  human.pedestrian.wheelchair: 'ignore'
  human.pedestrian.stroller: 'ignore'
  human.pedestrian.personal_mobility: 'ignore'
  human.pedestrian.police_officer: 'pedestrian'
  human.pedestrian.construction_worker: 'pedestrian'
  animal: 'ignore'
  vehicle.car: 'car'
  vehicle.motorcycle: 'motorcycle'
  vehicle.bicycle: 'bicycle'
  vehicle.bus.bendy: 'bus'
  vehicle.bus.rigid: 'bus'
  vehicle.truck: 'truck'
  vehicle.construction: 'construction_vehicle'
  vehicle.emergency.ambulance: 'ignore'
  vehicle.emergency.police: 'ignore'
  vehicle.trailer: 'trailer'
  movable_object.barrier: 'barrier'
  movable_object.trafficcone: 'traffic_cone'
  movable_object.pushable_pullable: 'ignore'
  movable_object.debris: 'ignore'
  static_object.bicycle_rack: 'ignore'
  flat.driveable_surface: 'driveable_surface'
  flat.other: 'other_flat'
  flat.sidewalk: 'sidewalk'
  flat.terrain: 'terrain'
  static.manmade: 'manmade'
  static.vegetation: 'vegetation'
  noise: 'ignore'
  static.other: 'ignore'
  vehicle.ego: 'ignore'

label_indices:
  'ignore': 0
  'barrier': 1
  'bicycle': 2
  'bus': 3
  'car': 4
  'construction_vehicle': 5
  'motorcycle': 6
  'pedestrian': 7
  'traffic_cone': 8
  'trailer': 9
  'truck': 10
  'driveable_surface': 11
  'other_flat': 12
  'sidewalk': 13
  'terrain': 14
  'manmade': 15
  'vegetation': 16

content:
  vehicle.emergency.ambulance : 2218 # 19
  animal : 5385 # 1
  human.pedestrian.personal_mobility : 8723 # 5
  human.pedestrian.stroller : 8809 # 7
  human.pedestrian.police_officer : 9159 # 6
  human.pedestrian.child : 9655 # 3
  human.pedestrian.wheelchair : 12168 # 8
  vehicle.emergency.police : 59590 # 20
  movable_object.debris : 66861 # 10
  human.pedestrian.construction_worker : 139443 # 4
  vehicle.bicycle : 141351 # 14
  static_object.bicycle_rack : 163126 # 13
  vehicle.bus.bendy : 357463 # 15
  vehicle.motorcycle : 427391 # 21
  movable_object.pushable_pullable : 718641 # 11
  movable_object.trafficcone : 736239 # 12
  static.other : 817150 # 29
  vehicle.construction : 1514414 # 18
  noise : 2061156 # 0
  human.pedestrian.adult : 2156470 # 2
  vehicle.bus.rigid : 4247297 # 16
  vehicle.trailer : 4907511 # 22
  flat.other : 8559216 # 25
  movable_object.barrier : 9305106 # 9
  vehicle.truck : 15841384 # 23
  vehicle.car : 38104219 # 17
  flat.sidewalk : 70197461 # 26
  flat.terrain : 70289730 # 27
  static.vegetation  : 122581273 # 30
  static.manmade : 178178063 # 28
  flat.driveable_surface : 316958899 # 24
  vehicle.ego : 337070621 # 31

class_division: # foreground(things) and background (stuff)
  foreground:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23

  background:
    - 0
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31


color_map: # RGB values for each class
  0: [0,0,0]
  1: [70,130,180]
  2: [0,0,230]
  3: [135,206,235]
  4: [100,149,237]
  5: [219,112,147]
  6: [0,0,128]
  7: [240,128,128]
  8: [138,43,226]
  9: [112,128,144]
  10: [210,105,30]
  11: [105,105,105]
  12: [47,79,79]
  13: [188,143,143]
  14: [220,20,60]
  15: [255,127,80]
  16: [255,69,0]
  17: [255,158,0]
  18: [233,150,70]
  19: [255,83,0]
  20: [255,215,0]
  21: [255,61,99]
  22: [255,140,0]
  23: [255,99,71]
  24: [0,207,191]
  25: [175,0,75]
  26: [75,0,75]
  27: [112,180,60]
  28: [222,184,135]
  29: [255,228,196]
  30: [0,175,0]
  31: [255,240,245]


learning_map :
  0: 0
  1: 0
  2: 2
  3: 2
  4: 2
  5: 0
  6: 2
  7: 0
  8: 0
  9: 9
  10: 0
  11: 0
  12: 10
  13: 0
  14: 3
  15: 5
  16: 5
  17: 1
  18: 7
  19: 0
  20: 0
  21: 4
  22: 8
  23: 6
  24: 11
  25: 12
  26: 13
  27: 14
  28: 15
  29: 0
  30: 16
  31: 0

#
#idx2name={0: 'noise', 1: 'animal', 2: 'human.pedestrian.adult', 3: 'human.pedestrian.child', 4: 'human.pedestrian.construction_worker',
#          5: 'human.pedestrian.personal_mobility', 6: 'human.pedestrian.police_officer', 7: 'human.pedestrian.stroller',
#          8: 'human.pedestrian.wheelchair', 9: 'movable_object.barrier', 10: 'movable_object.debris', 11: 'movable_object.pushable_pullable',
#          12: 'movable_object.trafficcone', 13: 'static_object.bicycle_rack', 14: 'vehicle.bicycle', 15: 'vehicle.bus.bendy',
#          16: 'vehicle.bus.rigid', 17: 'vehicle.car', 18: 'vehicle.construction', 19: 'vehicle.emergency.ambulance',
#          20: 'vehicle.emergency.police', 21: 'vehicle.motorcycle', 22: 'vehicle.trailer', 23: 'vehicle.truck',
#          24: 'flat.driveable_surface', 25: 'flat.other', 26: 'flat.sidewalk', 27: 'flat.terrain',
#          28: 'static.manmade', 29: 'static.other', 30: 'static.vegetation', 31: 'vehicle.ego'}
#
#
#
#learning_map_names = {0: 'ignore', 1: 'ignore', 2: 'pedestrian', 3: 'pedestrian', 4: 'pedestrian',
#                5: 'ignore', 6: 'pedestrian', 7: 'ignore', 8: 'ignore', 9: 'barrier',
#                10: 'ignore', 11: 'ignore', 12: 'traffic_cone', 13: 'ignore', 14: 'bicycle',
#                15: 'bus', 16: 'bus', 17: 'car', 18: 'construction_vehicle', 19: 'ignore',
#                20: 'ignore', 21: 'motorcycle', 22: 'trailer', 23: 'truck', 24: 'driveable_surface',
#                25: 'other_flat', 26: 'sidewalk', 27: 'terrain', 28: 'manmade', 29: 'ignore',
#                30: 'vegetation', 31: 'ignore'}
#
#mapping = { 'ignore': 0,'car': 1,'pedestrian': 2,  'bicycle': 3,'motorcycle': 4,
#           'bus': 5, 'truck': 6, 'construction_vehicle': 7,'trailer': 8, 'barrier': 9,
#            'traffic_cone': 10,'driveable_surface': 11, 'other_flat': 12,'sidewalk': 13,
#           'terrain': 14, 'manmade': 15,'vegetation': 16}


#import yaml
# nusc_config = yaml.safe_load(open('configs/nusc/lidarseg/nusc_config.yaml', 'r'))
# learning_map = nusc_config['learning_map']
# learning_map_inv = dict((y, x) for x, y in learning_map.items())

#for label,name in learning_map.items():
#    learning_map[label]=mapping[name]
